import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const TELEGRAM_INIT_MAX_AGE_SECONDS = 300;
const TELEGRAM_FUTURE_SKEW_SECONDS = 30;
function timingSafeEqualHex(a:string,b:string):boolean{if(!/^[0-9a-f]{64}$/i.test(a)||!/^[0-9a-f]{64}$/i.test(b))return false;let d=0;for(let i=0;i<64;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function verifyTelegramData(initData:string,botToken:string):Promise<any|null>{
 const p=new URLSearchParams(initData),h=p.get("hash"),ad=Number(p.get("auth_date"));if(!h||!Number.isInteger(ad))return null;
 const now=Math.floor(Date.now()/1000);if(ad>now+TELEGRAM_FUTURE_SKEW_SECONDS||now-ad>TELEGRAM_INIT_MAX_AGE_SECONDS)return null;
 p.delete("hash");const a:string[]=[];p.forEach((v,k)=>a.push(`${k}=${v}`));a.sort();
 const e=new TextEncoder(),sk=await crypto.subtle.importKey("raw",e.encode("WebAppData"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);
 const ss=await crypto.subtle.sign("HMAC",sk,e.encode(botToken)),fk=await crypto.subtle.importKey("raw",ss,{name:"HMAC",hash:"SHA-256"},false,["sign"]);
 const sig=await crypto.subtle.sign("HMAC",fk,e.encode(a.join("\n"))),ch=Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,"0")).join("");
 if(!timingSafeEqualHex(ch,h))return null;const u=p.get("user");if(!u)return null;try{return JSON.parse(u)}catch{return null}
}
Deno.serve(async req=>{const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:C});try{const BOT=Deno.env.get("TELEGRAM_BOT_TOKEN")!;const {initData,action,taskId,title,instructions,rewardAmount,taskUrl,taskType,provider,offerId,isActive,targetTelegramId,submissionId,status,comment}=await req.json();if(!initData)return new Response(JSON.stringify({error:"Missing initData"}),{status:400,headers:C});const tg=await verifyTelegramData(initData,BOT);if(!tg)return new Response(JSON.stringify({error:"Invalid Telegram data"}),{status:401,headers:C});const s=createClient(SUPABASE_URL,SERVICE_ROLE_KEY);if(String(tg.id)!=="1115177381")return new Response(JSON.stringify({error:"Access denied"}),{status:403,headers:C});
if(action==="list-tasks"){const {data,error}=await s.from("tasks").select("*").order("created_at",{ascending:false});if(error)throw error;return new Response(JSON.stringify({tasks:data}),{status:200,headers:{...C,"Content-Type":"application/json"}})}
if(action==="create-task"){if(!title||!instructions||!rewardAmount||!taskUrl)return new Response(JSON.stringify({error:"Missing task fields"}),{status:400,headers:C});const type=String(taskType||"manual").toLowerCase();if(!["manual","offer"].includes(type))return new Response(JSON.stringify({error:"Invalid task type"}),{status:400,headers:C});const p=type==="offer"?(provider?String(provider).toLowerCase():""):null;if(type==="offer"&&!p)return new Response(JSON.stringify({error:"Offer tasks require a provider"}),{status:400,headers:C});let parsedOfferId=offerId?String(offerId):null;if(p==="mobidea"&&!parsedOfferId){try{parsedOfferId=new URL(taskUrl).searchParams.get("offer_id")}catch{}}let target=targetTelegramId==null||targetTelegramId===""?null:Number(targetTelegramId);if(target!==null&&!Number.isSafeInteger(target))return new Response(JSON.stringify({error:"Invalid target Telegram ID"}),{status:400,headers:C});const {data:task,error}=await s.from("tasks").insert({title,instructions,reward_amount:rewardAmount,task_url:taskUrl,task_type:type,provider:p,offer_id:parsedOfferId,is_active:true,target_telegram_id:target}).select().single();if(error)throw error;const msg="🆕 New Task Available!\n\n📌 "+title+"\n💰 Reward: $"+Number(rewardAmount).toFixed(2)+" USDT\n\n👉 Open EasyTasksz to complete it now!";if(target!==null){fetch(`https://api.telegram.org/bot${BOT}/sendMessage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:target,text:msg})}).catch(()=>{});}else{fetch(`https://api.telegram.org/bot${BOT}/sendMessage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:"@EasyTaskszUpdates",text:msg})}).catch(()=>{});const {data:telegramUsers}=await s.from("users").select("telegram_id").not("telegram_id","is",null);Promise.all((telegramUsers||[]).map(({telegram_id})=>fetch(`https://api.telegram.org/bot${BOT}/sendMessage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:telegram_id,text:msg})}))).catch(()=>{});}return new Response(JSON.stringify({task}),{status:200,headers:{...C,"Content-Type":"application/json"}})}
if(action==="update-task"){if(!taskId)return new Response(JSON.stringify({error:"Missing taskId"}),{status:400,headers:C});const u:Record<string,unknown>={};if(title!==undefined)u.title=title;if(instructions!==undefined)u.instructions=instructions;if(rewardAmount!==undefined)u.reward_amount=rewardAmount;if(taskUrl!==undefined)u.task_url=taskUrl;if(taskType!==undefined)u.task_type=taskType?String(taskType).toLowerCase():"manual";if(provider!==undefined)u.provider=provider?String(provider).toLowerCase():null;if(offerId!==undefined)u.offer_id=offerId?String(offerId):null;if(isActive!==undefined)u.is_active=isActive;if(targetTelegramId!==undefined){const target=targetTelegramId==null||targetTelegramId===""?null:Number(targetTelegramId);if(target!==null&&!Number.isSafeInteger(target))return new Response(JSON.stringify({error:"Invalid target Telegram ID"}),{status:400,headers:C});u.target_telegram_id=target;}const {data:task,error}=await s.from("tasks").update(u).eq("id",taskId).select().single();if(error)throw error;return new Response(JSON.stringify({task}),{status:200,headers:{...C,"Content-Type":"application/json"}})}
if(action==="delete-task"){if(!taskId)return new Response(JSON.stringify({error:"Missing taskId"}),{status:400,headers:C});const {error:submissionsError}=await s.from("task_submissions").delete().eq("task_id",taskId);if(submissionsError)throw submissionsError;const {error:taskError}=await s.from("tasks").delete().eq("id",taskId);if(taskError)throw taskError;return new Response(JSON.stringify({success:true}),{status:200,headers:{...C,"Content-Type":"application/json"}})}
if(action==="list-submissions"){const {data,error}=await s.from("task_submissions").select("*, tasks(title, reward_amount), users(username, telegram_id)").order("created_at",{ascending:false});if(error)throw error;return new Response(JSON.stringify({submissions:data}),{status:200,headers:{...C,"Content-Type":"application/json"}})}
if(action==="review-submission"){
if(!submissionId||!status)return new Response(JSON.stringify({error:"Missing submissionId or status"}),{status:400,headers:C});
if(status!=="approved"&&status!=="rejected")return new Response(JSON.stringify({error:"Invalid submission status"}),{status:400,headers:C});
if(status==="rejected"&&!comment)return new Response(JSON.stringify({error:"Comment required for rejection"}),{status:400,headers:C});
const {data:result,error}=await s.rpc("process_task_submission_atomic",{p_submission_id:Number(submissionId),p_status:status,p_comment:comment??null});
if(error)throw error;
return new Response(JSON.stringify(result),{status:200,headers:{...C,"Content-Type":"application/json"}});
}
return new Response(JSON.stringify({error:"Unknown action"}),{status:400,headers:C})}catch(err){return new Response(JSON.stringify({error:String(err)}),{status:500,headers:C});}});