const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;const WEBHOOK_SECRET=Deno.env.get("TELEGRAM_WEBHOOK_SECRET")?.trim()||"";const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const GROQ=Deno.env.get("GROQ_API_KEY")?.trim()||"";const MODEL=Deno.env.get("GROQ_SUPPORT_MODEL")?.trim()||"openai/gpt-oss-20b";const MAX=1000,SESSION=30*60*1000,LIMIT=20;
function safe(a:string,b:string){if(!a||!b||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function fmt(s:string){return s.replace(/\\n/g,"\n").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\*\*(.+?)\*\*/gs,"<b>$1</b>")}
async function tg(m:string,b:any){if(m==="sendMessage"&&typeof b.text==="string"){b={...b,text:fmt(b.text),parse_mode:"HTML"}}return fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${m}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)})}
async function db(p:string,i:RequestInit){return fetch(`${SUPABASE_URL}/rest/v1/${p}`,{...i,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json",...(i.headers||{})}})}
async function session(id:number){const r=await db(`support_sessions?telegram_id=eq.${id}&select=telegram_id,active_until,history,message_count`,{method:"GET"});if(!r.ok)throw Error("session read failed");return (await r.json())[0]||null}
async function knowledge(telegramId:number){
 const sr=await db("settings?select=key,value,description,updated_at&order=key.asc",{method:"GET"});if(!sr.ok)throw Error("settings read failed");const s=await sr.json();
 const tr=await db("tasks?select=title,reward_amount,is_active,task_type,provider,created_at&is_active=eq.true&order=created_at.desc&limit=100",{method:"GET"});if(!tr.ok)throw Error("tasks read failed");const t=await tr.json();
 const safeS=s.filter((x:any)=>x.key&&x.key!=="support_kb_truth"&&x.key!=="referral_bonus"&&!/(secret|token|api[_-]?key|password|private[_-]?key)/i.test(x.key)).map((x:any)=>`SETTING ${x.key}: ${x.value}${x.description?" — "+x.description:""} (updated ${x.updated_at||"unknown"})`);
 const safeT=t.map((x:any)=>({title:String(x.title||"").slice(0,200),reward:x.reward_amount,type:x.task_type||"unknown",provider:x.provider||"unknown"}));
 const ur=await db("users?telegram_id=eq."+encodeURIComponent(String(telegramId))+"&select=referral_code",{method:"GET"});
 let referralLine="";
 if(ur.ok){const uu=await ur.json();const code=uu?.[0]?.referral_code;if(code) referralLine="USER-SPECIFIC REFERRAL LINK: https://t.me/Easytasksz_bot?startapp="+encodeURIComponent(String(code));}
 return ["CURRENT LIVE SETTINGS:",...safeS,"","CURRENT ACTIVE TASKS:",JSON.stringify(safeT),referralLine,"","VERIFIED RULES: Telegram authentication is required and auth data is fresh for 5 minutes. Support sessions last 30 minutes and allow 20 user messages. /stop ends a session. Only describe tasks listed above as currently active. Offer rewards can depend on provider confirmation/postback. The assistant cannot inspect private balances, transactions, withdrawal status, Telegram auth data, or admin controls. If information is not present in current data, never guess; direct the user to human support."].join("\n")
}
async function exact(q:string){const r=await db("settings?select=key,value&order=key.asc",{method:"GET"});if(!r.ok)return null;const a=await r.json();const m=[[/minimum\\s+withdrawal|withdrawal\\s+minimum|minimum.*cash.?out/i,"minimum_withdrawal","minimum withdrawal"," USDT"],[/withdrawal\\s+fee|cash.?out.*fee|fee.*withdrawal/i,"withdrawal_fee_percent","withdrawal fee","%"],[/daily.*ad.*limit|how many.*ads|ads.*per day/i,"daily_ad_limit","daily ad limit",""],[/reward.*per.*ad|how much.*ad|ad.*reward/i,"reward_per_ad","reward per ad"," USDT"],[/referral.*bonus|bonus.*referral/i,"referral_bonus","referral bonus"," USDT"],[/referral.*commission|commission.*referral/i,"referral_commission_percent","referral commission","%"]];const n=q.toLowerCase().replace(/[^a-z0-9 ]/g," ").replace(/ +/g," ").trim();let x=m.find(v=>v[0].test(n));if(!x && (n.includes("minimum withdrawal")||n.includes("withdrawal minimum"))){x=m[0]}if(!x)return null;const row=a.find((v:any)=>v.key===x[1]);return row?.value!=null?`The current ${x[2]} is ${row.value}${x[3]}.`:null}
function overview(s:any[],t:any[]){
 const v=(k:string)=>s.find((x:any)=>x.key===k)?.value;
 let out="**EasyTasksz** is a Telegram-based earning platform.\\n\\n**What you can do**\\n\\n- **Tasks & offers:** Complete tasks and offers that appear in the app.\\n";
 if(v("ads_enabled")==="true") out+=`- **Rewarded ads:** Watch up to **${v("daily_ad_limit")} ads per day** and earn **${v("reward_per_ad")} USDT** per completed ad.\\n`;
 else out+="- **Rewarded ads:** Currently disabled.\\n";
 out+="\\n**Referral program**\\n";
 out+=`- **Referral commission:** ${v("referral_commission_percent")}% of referred-user earnings.\\n\\n`;
 out+="**Withdrawals**\\n";
 if(v("withdrawals_enabled")==="true") out+=`- **Minimum withdrawal:** ${v("minimum_withdrawal")} USDT.\\n- **Withdrawal fee:** ${v("withdrawal_fee_percent")}%.\\n`;
 else out+="- Withdrawals are currently disabled.\\n";
 if(t.length) out+="\\n**Currently active tasks**\\n"+t.slice(0,8).map((x:any)=>`- ${x.title} — **${x.reward}**`).join("\\n")+"\\n";
 else out+="\\n**Current status**\\n- No active tasks are listed at the moment.\\n";
 return out.trim();
}
async function ask(h:any[],telegramId:number){if(!GROQ)throw Error("no groq");const k=await knowledge(telegramId);const sys=`You are the EasyTasksz Telegram support assistant. Be concise, friendly, factual, and well organized. Use ONLY the CURRENT LIVE DATA below. Live settings override old knowledge and conversation history. Never guess. Never invent availability, rewards, fees, limits, eligibility or processing times. If current data does not answer the question, say so and direct the user to human support. Never expose private account data or secrets. Never give bypass instructions. EasyTasksz does NOT pay a referral bonus. Never state, imply, or invent any referral bonus; only the current referral commission applies.

TELEGRAM RESPONSE FORMAT:
- Never use Markdown tables or pipe characters for tables.
- Never write long blocks of text.
- Use short sections with a clear heading when useful.
- Use bullet points for multiple items.
- Use **bold** for important values or labels.
- Leave a blank line between sections.
- For broad questions, keep the answer easy to scan and normally under 8 bullet points.
- Give the direct answer first, then brief supporting details.
- Do not add unnecessary greetings or repeated disclaimers.
- Do not use Markdown links unless the user asks for a link.
- The system will convert **bold** formatting into Telegram bold text.\n\nCURRENT LIVE DATA:\n${k}`;const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${GROQ}`,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,messages:[{role:"system",content:sys},...h],temperature:.2,max_completion_tokens:500})});const d=await r.json();if(!r.ok)throw Error(`groq ${r.status}: ${d?.error?.message||"error"}`);const x=d?.choices?.[0]?.message?.content;if(!x)throw Error("empty groq");return x.trim().slice(0,3500)}
Deno.serve(async req=>{try{if(req.method!=="POST")return new Response("Method not allowed",{status:405});if(!WEBHOOK_SECRET||!safe(req.headers.get("X-Telegram-Bot-Api-Secret-Token")||"",WEBHOOK_SECRET))return new Response("Unauthorized",{status:401});const u=await req.json(),m=u.message;if(!m?.text)return new Response("ok");const id=Number(m.chat?.id),q=String(m.text).trim();if(!Number.isSafeInteger(id))return new Response("ok");
if(/^\/start(?:@\w+)?$/i.test(q)){const sr=await db("settings?select=key,value&order=key.asc",{method:"GET"});let s:any[]=[];if(sr.ok)s=await sr.json();const v=(k:string)=>s.find((x:any)=>x.key===k)?.value;const name=String(m.from?.first_name||"there").replace(/[<&>]/g,"");let x="🎉 Welcome to EasyTasksz!\n\nHello, "+name+"!\n\n💰 Complete available tasks and offers to earn USDT\n";if(v("ads_enabled")==="true")x+="📺 Watch up to "+(v("daily_ad_limit")||"0")+" rewarded ads per day and earn "+(v("reward_per_ad")||"0")+" USDT per ad\n";x+="👥 Earn "+(v("referral_commission_percent")||"0")+"% referral commission from referred-user earnings\n💸 Minimum withdrawal: "+(v("minimum_withdrawal")||"0")+" USDT\n🤖 Need help? Use /support\n\n👇 Tap below to open EasyTasksz and start earning!";await tg("sendMessage",{chat_id:id,text:x,reply_markup:{inline_keyboard:[[{text:"🚀 OPEN EASYTASKSZ",url:"https://t.me/Easytasksz_bot?startapp"}]]}});return new Response("ok")}
if(/^\/support(?:@\w+)?$/i.test(q)){await db("support_sessions",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({telegram_id:id,active_until:new Date(Date.now()+SESSION).toISOString(),history:[],message_count:0,updated_at:new Date().toISOString()})});await tg("sendMessage",{chat_id:id,text:"🤖 EasyTasksz Support is ready. Ask me your question.\n\nThis support session stays active for 30 minutes. Use /stop to end it."});return new Response("ok")}
if(/^\/stop(?:@\w+)?$/i.test(q)){await db(`support_sessions?telegram_id=eq.${id}`,{method:"DELETE"});await tg("sendMessage",{chat_id:id,text:"Support chat ended. Use /support whenever you need help again."});return new Response("ok")}
const s=await session(id);if(!s||new Date(s.active_until).getTime()<=Date.now()){await tg("sendMessage",{chat_id:id,text:"Use /support to start an EasyTasksz support chat."});return new Response("ok")}if(q.length<1||q.length>MAX){await tg("sendMessage",{chat_id:id,text:`Please keep your support message under ${MAX} characters.`});return new Response("ok")}const n=Number(s.message_count||0);if(n>=LIMIT){await tg("sendMessage",{chat_id:id,text:"This support session has reached its message limit. Use /support to start a new session."});return new Response("ok")}
const cleanHistory=(Array.isArray(s.history)?s.history:[]).filter((x:any)=>!String(x?.content||"").toLowerCase().includes("referral bonus"));const h=[...cleanHistory,{role:"user",content:q}].slice(-12);let a;try{const broad=/tell me more|about eas(?:y)?tasksz|what is eas(?:y)?tasksz|how does eas(?:y)?tasksz work|what can i do/i.test(q.toLowerCase());if(broad){const sr=await db("settings?select=key,value,description,updated_at&order=key.asc",{method:"GET"});const tr=await db("tasks?select=title,reward_amount,is_active,task_type,provider,created_at&is_active=eq.true&order=created_at.desc&limit=100",{method:"GET"});if(!sr.ok||!tr.ok)throw Error("live data read failed");a=overview(await sr.json(),(await tr.json()).map((x:any)=>({title:String(x.title||"").slice(0,200),reward:x.reward_amount,type:x.task_type||"unknown",provider:x.provider||"unknown"})))}else a=await exact(q)||await ask(h,id)}catch(e){console.error(e);await tg("sendMessage",{chat_id:id,text:"Sorry, support AI is temporarily unavailable. Please try again shortly."});return new Response("ok")}
const nh=[...h,{role:"assistant",content:a}].slice(-12);await db(`support_sessions?telegram_id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({active_until:new Date(Date.now()+SESSION).toISOString(),history:nh,message_count:n+1,updated_at:new Date().toISOString()})});await tg("sendMessage",{chat_id:id,text:a});return new Response("ok")}catch(e){console.error(e);return new Response("ok")}});