alter table public.tasks add column if not exists provider text;
alter table public.tasks add column if not exists offer_id text;

create table if not exists public.mobidea_clicks (
  id bigint generated by default as identity primary key,
  click_id text not null,
  user_id bigint not null references public.users(id) on delete cascade,
  task_id integer not null references public.tasks(id) on delete cascade,
  offer_id text not null,
  created_at timestamptz not null default now(),
  converted_at timestamptz,
  payout_usd numeric,
  status text not null default 'pending' check (status in ('pending','converted'))
);

create unique index if not exists mobidea_clicks_click_id_key on public.mobidea_clicks(click_id);
create index if not exists mobidea_clicks_user_id_idx on public.mobidea_clicks(user_id);
create index if not exists mobidea_clicks_task_id_idx on public.mobidea_clicks(task_id);

create or replace function public.process_mobidea_conversion(p_click_id text, p_payout_usd numeric)
returns table(processed boolean, user_id bigint, user_share numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_click public.mobidea_clicks%rowtype;
  v_user public.users%rowtype;
  v_user_share numeric;
  v_commission_percent numeric;
  v_commission numeric;
begin
  if p_click_id is null or length(p_click_id) < 8 or length(p_click_id) > 32 then
    return query select false, null::bigint, 0::numeric;
    return;
  end if;
  if p_payout_usd is null or p_payout_usd < 0 then
    return query select false, null::bigint, 0::numeric;
    return;
  end if;

  select * into v_click
  from public.mobidea_clicks
  where click_id = p_click_id
  for update;

  if not found then
    return query select false, null::bigint, 0::numeric;
    return;
  end if;

  if v_click.status = 'converted' then
    return query select false, v_click.user_id, 0::numeric;
    return;
  end if;

  select * into v_user from public.users where id = v_click.user_id for update;
  if not found then
    return query select false, null::bigint, 0::numeric;
    return;
  end if;

  v_user_share := round(p_payout_usd * 0.60, 6);

  update public.users
  set balance = coalesce(balance, 0) + v_user_share,
      total_earned = coalesce(total_earned, 0) + v_user_share
  where id = v_user.id;

  if v_user.referred_by is not null then
    select coalesce((select value::numeric from public.settings where key = 'referral_commission_percent' limit 1), 3)
      into v_commission_percent;
    v_commission := v_user_share * (v_commission_percent / 100);
    perform public.add_referral_commission(v_user.referred_by, v_commission);
  end if;

  update public.mobidea_clicks
  set status = 'converted',
      converted_at = now(),
      payout_usd = p_payout_usd
  where id = v_click.id;

  return query select true, v_user.id, v_user_share;
end;
$$;
