create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  target_type text not null default 'all',
  bonus_enabled boolean not null default false,
  bonus_amount numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table public.campaigns drop constraint if exists campaigns_target_type_check;
alter table public.campaigns add constraint campaigns_target_type_check
  check (target_type in ('all', 'new', 'not_received'));
alter table public.campaigns drop constraint if exists campaigns_bonus_amount_check;
alter table public.campaigns add constraint campaigns_bonus_amount_check
  check (bonus_amount >= 0);

create table if not exists public.campaign_user_records (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.campaigns(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  bonus_given boolean not null default false,
  notification_sent boolean not null default false,
  notification_error text,
  created_at timestamptz not null default now(),
  unique (campaign_id, user_id)
);

create index if not exists campaign_user_records_campaign_idx
  on public.campaign_user_records(campaign_id);
create index if not exists campaign_user_records_user_idx
  on public.campaign_user_records(user_id);

create or replace function public.apply_campaign_bonus(
  p_campaign_id bigint,
  p_user_id bigint,
  p_amount numeric
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed boolean := false;
begin
  if p_amount is null or p_amount <= 0 then
    return false;
  end if;

  update public.campaign_user_records
     set bonus_given = true
   where campaign_id = p_campaign_id
     and user_id = p_user_id
     and bonus_given = false;

  claimed := found;
  if not claimed then
    return false;
  end if;

  update public.users
     set balance = coalesce(balance, 0) + p_amount,
         total_earned = coalesce(total_earned, 0) + p_amount
   where id = p_user_id;

  return true;
end;
$$;

revoke all on function public.apply_campaign_bonus(bigint, bigint, numeric) from public;
